server:
  port: 8080
  error:
    include-message: always

aspect:
  rate-limited:
    enabled: true

resilience4j.ratelimiter:
  configs:
    calculations-distance:
      limitForPeriod: 10
      limitRefreshPeriod: 60s
      timeoutDuration: 0
      eventConsumerBufferSize: 5